# configs/train.yaml

experiment:
  seed: 41                   # random seed
  base_dir: "./data/busi"    # dir
  train_file_dir: "busi_train.txt" # dir
  val_file_dir: "busi_val.txt"     # dir

model:
  name: "SwinUnet"           # model_name, see in src/tils/modelloader/MODEL_REGISTRY 改天修改为新的地方.
  num_classes: 1             # seg num_classes
  img_size: 256              # img size of per batch (SwinUnet 内部一般会覆盖为 224)
  
  # ==============================
  # 专门给 SwinUnet 留的参数
  # ==============================
  cfg: "src/network/swinUnet/swin_tiny_patch4_window7_224_lite.yaml" # path to config file
  zip: false                 # use zipped dataset instead of folder dataset
  opts: null                 # Modify config options by adding 'KEY VALUE' pairs.
  cache_mode: "part"         # no: no cache, full: cache all data, part: sharding the dataset into nonoverlapping pieces and only cache one piece
  resume: null               # resume from checkpoint
  accumulation_steps: null   # gradient accumulation steps
  use_checkpoint: false      # whether to use gradient checkpointing to save memory
  amp_opt_level: "O1"        # mixed precision opt level, if O0, no amp is used
  tag: null                  # tag of experiment
  eval: false                # Perform evaluation only
  throughput: false          # Test throughput only

train:
  epoch: 300                 # train epoch
  batch_size: 4              # batch_size per gpu
  base_lr: 0.01              # segmentation network learning rate